### ISSUE TITLE
Problems with Kazari

### ISSUE THREAD

**Issue by anamariamv** [47deg/freestyle#185]
We need to resolve the problem of Kazari. 
Only the first compilation works.

**Comment by dominv** [comment]
The code must be organized like this:

```scala
import freestyle._
import freestyle.implicits._

object algebras {
  @free trait Validation[F[_]] {
    def minSize(s: String, n: Int): FreeS.Par[F, Boolean]
    def hasNumber(s: String): FreeS.Par[F, Boolean]
  }

  @free trait Interaction[F[_]] {
    def tell(msg: String): FreeS[F, Unit]
    def ask(prompt: String): FreeS[F, String]
  }
}

object modules {
  import algebras._
  
  @module trait Application[F[_]] {
    val validation: Validation[F]
    val interaction: Interaction[F]
  }
}

import modules._
import algebras._

def program[F[_]](implicit A: Application[F]) = {
  import A._
  import cats.implicits._

  for {
    userInput <- interaction.ask("Give me something with at least 3 chars and a number on it")
    valid <- (validation.minSize(userInput, 3) |@| validation.hasNumber(userInput)).map(_ && _).freeS
    _ <- if (valid)
            interaction.tell("awesomesauce!") 
         else
            interaction.tell(s"$userInput is not valid")
  } yield ()
}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

implicit val validationHandler = new Validation.Handler[Future] {
  override def minSize(s: String, n: Int): Future[Boolean] = Future(s.size >= n)
  override def hasNumber(s: String): Future[Boolean] = Future(s.exists(c => "0123456789".contains(c)))
}

implicit val interactionHandler = new Interaction.Handler[Future] {
  override def tell(s: String): Future[Unit] = Future.successful(println(s))
  override def ask(s: String): Future[String] = Future.successful { println(s); "This could have been user input 1" }
}

import cats.implicits._
import scala.concurrent.duration.Duration
import scala.concurrent.Await

val futureValue = program[Application.Op].exec[Future]
Await.result(futureValue, Duration.Inf) //blocking only for demo purposes. Don't do this at home.
```

**Comment by raulraja** [comment]
This is a valid way to organize, so let's use that if that is the issue. We need to understand why it's not working otherwise. Is it an implicit resolution issue? Can we see some stack traces with the errors? This is now blocking 0.1.0 and we need to get this solved asap.

**Comment by dominv** [comment]
The error message I'm getting, when I'm not using the objects, is the following one:
```
exception during macro expansion: 
scala.ScalaReflectionException: <none> is not a class
	at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
	at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:88)
	at freestyle.openUnion$.materializeImpl(module.scala:92)
```
The line 92 in `module.scala` is:
```scala
    val algebras   = findAlgebras(weakTypeOf[A].typeSymbol.companion.asClass)
```
And its failing when it calls to the companion method:
```
weakTypeOf[A]: Application.type
weakTypeOf[A].typeSymbol: object Application
weakTypeOf[A].typeSymbol.companion: <none>
```

On the other hand, when using objects, the results are:
```
weakTypeOf[A]: Evaluator__3b8302c6c45f12ee4172cc7128601deeeff5e5d0_1123939886.modules.Application.type
weakTypeOf[A].typeSymbol: object Application
weakTypeOf[A].typeSymbol.companion: trait Application
```

**Comment by raulraja** [comment]
This is still an issue. Kazari is not working in the main doc site.

**Comment by juanpedromoreno** [comment]
Potentially it's due to empty snapshot jars.

**Comment by dominv** [comment]
@raulraja @juanpedromoreno It seems to be working now. Although I believe we should keep this issue open until we find why it doesn't work without the objects.

**Comment by raulraja** [comment]
@dominv let's try with latest since now we depend on scalameta.

**Comment by dominv** [comment]
So far, I'm getting an error when I send any POST request including the 'Scalameta Paradise Plugin' dependency. (The 'evaluator' already adds 'paradise' as a compiler plugin if it's specified in the dependencies).

An simple example request could be:

```json
{
	"resolvers":["https://oss.sonatype.org/content/repositories/releases"],
	"dependencies":[
		{
			"groupId":"org.scalameta",
			"artifactId":"paradise_2.12.2",
			"version":"3.0.0-M9"
		}],
    "code":"List(1, 3, 5)"
}
```
The evaluator throws the error:
```scala
java.lang.NullPointerException
	at io.circe.Printer.printJsonString(Printer.scala:172)
	at io.circe.Printer.printJsonAtDepth(Printer.scala:231)
	at io.circe.Printer.printJsonObjectAtDepth(Printer.scala:204)
	at io.circe.Printer.printJsonAtDepth(Printer.scala:234)
	at io.circe.Printer.pretty(Printer.scala:244)
	at org.scalaexercises.evaluator.Http4sCodecInstances$$anonfun$1.apply(codecs.scala:32)
	at org.scalaexercises.evaluator.Http4sCodecInstances$$anonfun$1.apply(codecs.scala:31)
	at org.http4s.EntityEncoder$$anon$2.toEntity(EntityEncoder.scala:37)
	at org.http4s.EntityEncoder$$anon$3.toEntity(EntityEncoder.scala:49)
	at org.http4s.dsl.impl.EntityResponseGenerator$class.apply(ResponseGenerator.scala:44)
	at org.http4s.dsl.package$OkSyntax.apply(package.scala:83)
	at org.http4s.dsl.impl.EntityResponseGenerator$class.apply(ResponseGenerator.scala:40)
	at org.http4s.dsl.package$OkSyntax.apply(package.scala:83)
	at org.scalaexercises.evaluator.services$$anonfun$evalService$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(services.scala:72)
	at org.scalaexercises.evaluator.services$$anonfun$evalService$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(services.scala:49)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:457)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:118)
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:91)
	at scalaz.Free.resume(Free.scala:109)
	at scalaz.Free.go2$1(Free.scala:153)
	at scalaz.Free.go(Free.scala:157)
	at scalaz.Free.run(Free.scala:263)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:428)
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:428)
	at scalaz.concurrent.Future$$anonfun$timed$1$$anonfun$apply$7.apply(Future.scala:261)
	at scalaz.concurrent.Future$$anonfun$timed$1$$anonfun$apply$7.apply(Future.scala:261)
	at scalaz.concurrent.Future$$anonfun$unsafePerformAsyncInterruptibly$1.apply(Future.scala:172)
	at scalaz.concurrent.Future$$anonfun$unsafePerformAsyncInterruptibly$1.apply(Future.scala:172)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListenInterruptibly$1.apply(Future.scala:98)
	at scalaz.concurrent.Future$$anonfun$unsafePerformListenInterruptibly$1.apply(Future.scala:97)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

I believe it's related with this issue https://github.com/scalameta/paradise/issues/10 currently opened in 'Scalameta Paradise Plugin' 

I've also checked myself that the plugin is not currently working in the console with:
**build.sbt**
```scala 
scalaVersion := "2.12.2"
addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M9" cross CrossVersion.full)
```
I'm getting the error: 
```scala
> console
[info] Starting scala interpreter...
[info] 
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/Object.class)
[error] (run-main-0) java.lang.reflect.InvocationTargetException
```

**Comment by dominv** [comment]
@raulraja what's your opinion about this?

**Comment by dominv** [comment]
This issue has been solved updating the evaluator to the last scala version used in freestyle-docs. 
A new issue to integrate Kazari in the docs has been created https://github.com/frees-io/freestyle-docs/issues/22
